patient=('Tinah',21,"120/80",72)age=patient[1]weight=patient[3]print("age:",age)print("weight",weight)print(patient)patient_list=list(patient)patient_list[2]=135/80patient=tuple(patient_list)print(patient)patients=(    ("Tinah",30,72,65.5),    ("vee",34,56,82.0),    ("lee",56,76,70.5),    ("joe",35,75,68.0))patient_names=[patient[0] for patient in patients]print("patient namess:",patient_names)